config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'homes#top'
  get "search" => "posts#search"
  get "ranking" => "posts#ranking"
  get 'homes/top'
  get 'homes/about'
  resources :posts do
  	resource :likes, only: [:create, :destroy]
  	resources :comments, only: [:create, :destroy]
  end
  resources :users
  resources :relationships, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true, length: { maximum: 300 }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.build(comment_params)
      @comment.user_id = current_user.id
      @comment.save
      render :index
    end

    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      render :index
    end

    private
    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment], url: post_comments_path(@post) ) do |f| %>
    <%= f.text_area :content, class: "form-control" %>
    <%= f.submit "送信", class: "btn btn-outline-dark float-right" %>
<% end %>

app/views/comments/_index.html.erb
<h3 class="comment-line"><i class="fa fa-comment"><%= comments.count %>件コメント</i></h3>
<div class="row">
  <table class="table">
    <% comments.first(3).each do |comment| %>
        <% unless comment.id.nil? %>
        <tr>
        <% if comment.user.user_image? %>
          <td><%= image_tag comment.user.user_image.url, class: "rounded-circle", size: "100x100"%></td>
        <% else %>
          <td><img src="/assets/no_image.jpg" class="rounded-circle" alt="Card image cap" width="100" height="100"></td>
        <% end %>
          <td><%= link_to user_path(comment.user.id) do %>
                   <%= comment.user.name %>
              <% end %>
          </td>
          <td><%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
          <td><%= comment.content %></td>
          <% if comment.user == current_user %>
            <td><%= link_to post_comment_path(comment.post_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
              <i class="fas fa-trash" style="color: black;"></i>
            </td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>
<a data-toggle="collapse" href="#example1" aria-expanded="false" aria-controls="example1">もっと見る</a>
<div class="collapse" id="example1">
  <div class="row">
      <table class="table">
        <% comments.offset(3).each do |comment| %>
          <% unless comment.id.nil? %>
            <tr>
              <% if comment.user.user_image? %>
                <td><%= image_tag comment.user.user_image.url, class: "rounded-circle", size: "100x100"%></td>
              <% else %>
                <td><img src="/assets/no_image.jpg" class="rounded-circle" alt="Card image cap" width="100" height="100"></td>
              <% end %>
              <td><%= "#{comment.user.name}" %></td>
              <td><%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
              <td><%= comment.content %></td>
              <% if comment.user == current_user %>
                <td><%= link_to post_comment_path(comment.post_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                  <i class="fas fa-trash" style="color: black;"></i>
                </td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </table>
  </div>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.post.comments }) %>")
$("text_area").val('')