config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'homes#top'
  get "search" => "posts#search"
  get "ranking" => "posts#ranking"
  get 'homes/top'
  get 'homes/about'
  resources :posts do
  	resource :likes, only: [:create, :destroy]
  	resources :comments, only: [:create, :destroy]
  end
  resources :users
  resources :relationships, only: [:create, :destroy]
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  	@posts = Post.all.order(created_at: :desc)
  	@post = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end

  def about
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
  <div class="top-container">
    <div class="row">
      <h3 class="top-content">Map</h3>
    </div>
    <div class="row">
      <p class="top-content-name">
        <% if user_signed_in? %>
          ようこそ！！<%= current_user.name %>さん
        <% else %>
          <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %>
        <% end %>
      </p>
    </div>

    <div class="container">
      <h3 class="top-list"><i class="fas fa-camera"></i>新着投稿</h3>
        <div class="row">
        <% @posts.first(3).each do |post| %>
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <% if post.image? %>
                <%= image_tag post.image.url, class: "card-img-top", size: "287x225"%>
              <% else %>
                <img src="/assets/default.png" class="card-img-top" alt="Card image cap" width="287" height="225">
              <% end %>
              <div class="card-body">
                <p class="card-text">
                  <strong>タイトル：<%= post.title %></strong><br>
                  <strong>地域　　：</strong><%= post.place %><br>
                  <strong>予算　　：</strong><%= post.budget %>
                </p>
                <div class="d-flex justify-content">
                    <div id="likes_buttons_<%= post.id %>">
                      <%= render partial: 'likes/like', locals: { post: post} %>
                    </div>
                  <div class="btn-position">
                    <%= link_to "詳細", post_path(post), class: "btn btn-sm btn-outline-secondary" %>
                  </div>
                  <small class="text-muted">投稿日時：<%= post.created_at.strftime('%Y/%m/%d') %></small>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        </div>
    </div>
    <div style="text-align:center;">
        <%= link_to 'ランキングを見る', ranking_path, class: "btn page-link text-dark d-inline-block rounded-pill"  %>
    </div>
    <div class="container">
      <h3 class="top-list"><i class="fas fa-crown" style="color: black;"></i>人気ランキング</h3>
        <div class="row">
        <% @post.each do |post| %>
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <% if post.image? %>
                <%= image_tag post.image.url, class: "card-img-top", size: "287x225"%>
              <% else %>
                <img src="/assets/default.png" class="card-img-top" alt="Card image cap" width="287" height="225">
              <% end %>
              <div class="card-body">
                <p class="card-text">
                  <strong>タイトル：<%= post.title %></strong><br>
                  <strong>地域　　：</strong><%= post.place %><br>
                  <strong>予算　　：</strong><%= post.budget %>
                </p>
                <div class="d-flex justify-content">
                  <div id="likes_buttons_<%= post.id %>">
                     <%= render partial: 'likes/like', locals: { post: post} %>
                  </div>
                  <div class="btn-position">
                    <%= link_to "詳細", post_path(post), class: "btn btn-sm btn-outline-secondary" %>
                  </div>
                  <small class="text-muted">投稿日時：<%= post.created_at.strftime('%Y/%m/%d') %></small>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        </div>
    </div>
    <div style="text-align:center;">
        <%= link_to '新着投稿を見る', posts_path, class: "btn page-link text-dark d-inline-block rounded-pill"  %>
    </div>