config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'homes#top'
  get "search" => "posts#search"
  get "ranking" => "posts#ranking"
  get 'homes/top'
  get 'homes/about'
  resources :posts do
  	resource :likes, only: [:create, :destroy]
  	resources :comments, only: [:create, :destroy]
  end
  resources :users
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div class="alert alert-warning">
        <ul>
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Map</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= include_gon %>
  <script src="https://kit.fontawesome.com/bd2127829f.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/flash' %>
    <div class="search-icon" data-toggle="modal" data-target="#modal1">
        <i class="fa fa-search fa-3x", style="color:black;"></i>
    </div>
  <div class="modal" id="modal1" tabindex="-1" role="dialog" aria-labelledby="staticModalLabel" aria-hidden="true" data-show="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">検索画面</h4>
          <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&#215;</span>
          </button>
        </div>
        <div class="modal-body">
          <p class="recipient">観光スポット名を入力してください</p>
          <div class="search-form">
            <%= form_tag(search_path,:method => 'get') do %>
              <%= text_field_tag :search %>
              <%= submit_tag '検索', :name => nil %>
            <% end %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
        </div>
      </div>
    </div>
  </div>
    <div id="sp-menu">
      <% if user_signed_in? %>
        <ul style="margin-top:0px;">
          <li><i class="fa fa-user fa-2x"></i><%= link_to '　マイページ', user_path(current_user.id) %></li>
          <li><i class="fa fa-home fa-2x"></i><%= link_to '　トップページ', homes_top_path %></li>
          <li><i class="fa fa-sticky-note-o fa-2x"></i><%= link_to '　About', homes_about_path %></li>
          <li><i class="fa fa-pencil-square-o fa-2x"></i> <%= link_to '　投稿', new_post_path %></li>
          <li><i class="fa fa-crown fa-2x"></i><%= link_to '　ランキング', ranking_path %></li>
          <li><i class="fa fa-list fa-2x"></i><%= link_to '　新着一覧', posts_path %></li>
          <li><i class="fa fa-sign-out fa-2x"></i><%= link_to '　ログアウト',destroy_user_session_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul style="margin-top:0px;">
          <li><i class="fa fa-home fa-2x"></i><%= link_to '　トップページ', homes_top_path %></li>
          <li><i class="fa fa-sticky-note-o fa-2x"></i><%= link_to '　About', homes_about_path %></li>
          <li><i class="fa fa-list fa-2x"></i><%= link_to '　投稿一覧', posts_path %></li>
          <li><i class="fa fa-sign-in fa-2x"></i><%= link_to '　ログイン', new_user_session_path %></li>
          <li><i class="fa fa-user fa-2x"></i><%= link_to '　新規登録', new_user_registration_path %></li>
        </ul>
      <% end %>
    </div>
    <div id="hm-icon">
      <a class="menu-trigger" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>
  <%= yield %>


  <footer>
    <p class="footer-text">© 2020 - map </p>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>